spring:
  application:
    name: M2J2
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//hi.newlecture.com:1521/XEPDB1
    username: M2J2
    password: dpaxnwpdlxn

server:
  port: 8080
#  address: ...


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: com.m2j2.haruseoul.entity
  logging:
    level:
      com.m2j2.haruseoul.repository: trace